
---
version: '3.8'
services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: alex
  apache:
    image: httpd
    ports:
      - 8888:80
    links:
      - mydb:mysql

  php:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - apache:httpd
...
