
---
version: '3'
services:
  mydb:
    images: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: alex
  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    links:
      - mydb:mysql
...
