---
version: '3.8'

services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: alex

  apache:
    image: httpd
    ports:
      - 7070:8080
    links:
      - mydb:mysql
    container_name: mydb

  php:
    image: php:7.2-apache
    links:
      - mydb:mysql
    container_name: php
...